### ISSUE TITLE
Auto detect and download terraform

### ISSUE THREAD

**Issue by leg100** [leg100/pug#11]
Automatically detect required terraform version and download.

**Comment by nokernel** [comment]
Food for tough, for the last coupld of years I have been doing this with bash by looking at the terraform -> required_version. It works pretty well and does not require custom file.

**Comment by davidjeddy** [comment]
Another option, use version manager such as https://github.com/tfutils/tfenv or https://github.com/tofuutils/tofuenv . They are able to read the required_version attributes by design. Additionally these tools can install latest, ENV VAR value, or .terraform-version/.tofu-version if so desired.

**Comment by leg100** [comment]
Hello @davidjeddy,

@nokernel and I tried out https://github.com/tofuutils/tenv, a "successor"
to the tools you've listed. It mostly works, if you set it as the program
for pug to use via the program flag - `pug --program=tenv` - but we
encountered a few issues:

* It didn't work concurrently, but I raised an issue with them and they
promptly fixed that: https://github.com/tofuutils/tenv/issues/116
* If your HCL is invalid then it'll fail to read the required_version,
whereas @nokernel's bash script had no problem reading it. This is a
problem, say, if you're running `terraform validate` via pug because you're
checking whether your HCL is valid.
* When tenv downloads terraform it spits out a load of messaging to stdout.
This can confuse pug, because pug sometimes reads the stdout of terraform
processes, for example, the output from `workspace list` from which it
loads a list of workspaces.

So only a couple of unresolved issues and not majorly concerning. But
something to be aware of.

I've also tried pug with terraform sourced from https://asdf-vm.com/ and
https://mise.jdx.dev/. I can report these both work fine (in the case of
`mise` you need to use shims).

In terms of addressing this issue, we can do one or more of the following:

* Add the above notes to the README
* Contact tenv team to see what they can do about the other two issues
* Build functionality directly into pug.

**Comment by ohmer** [comment]
Just my .2c, I don't think this feature should be part of pug. I like the Unix philosophy of combining simple tools.
Been using `asdf` for years now btw.

Maybe what could be useful is an arbitrary command executor in a selected list of directory, with ability to sequence or parallelize. Would allow `tfenv / tgenv / asdf install` en masse or `terraform init -upgrade` (which I am missing too)

What do you think?

**Comment by leg100** [comment]
> Just my .2c, I don't think this feature should be part of pug. I like the Unix philosophy of combining simple tools.
Been using asdf for years now btw.

I completely agree. I've been meaning to write something in the README to this effect and then close this issue.

> Maybe what could be useful is an arbitrary command runner in a selected list of directories, with the ability to sequence or parallelize tasks. Would allow tfenv / tgenv / asdf install en masse or terraform init -upgrade (which I am missing too)

I'm not sure what you mean, can you elaborate?

**Comment by ohmer** [comment]
> > Maybe what could be useful is an arbitrary command runner in a selected list of directories, with the ability to sequence or parallelize tasks. Would allow tfenv / tgenv / asdf install en masse or terraform init -upgrade (which I am missing too)
> 
> I'm not sure what you mean, can you elaborate?

I mean that you implemented classic `terraform` actions like `init` / `plan` / `apply`. What if I want to run something else in the directory of a set of stacks (or root modules in `pug`) ? It would bypass the `--program` switch and result in executing a command of my choice.

Example: I want to download and install `terraform` which version is controlled by a version manager. The simple use case is when there is only one configuration file at the root of the repository. As a developer, I just have to run `asdf install terraform` or `tfenv install` or whatever your version manager dictactes. There is not much need for an additional tool here. But there is a more complex scenario where there are many version manager configuration files. For instance, you can override a `terraform` version configuration in a subdirectory. The version manager does the version resolution in the cnotext of the stack. Say you have `/.terraform-version` = `1.7.5` and `/this/old/dev/stack/.terraform-version` = `1.0.11`. It would be handy to run `asdf install terraform` or `tfenv install`... in each directory.

For the `init -upgrade` command, this feature would also help. It is not part of the keybindings as far as I have seen so upgrading providers and modules on a large number of stacks is not possible with `pug`.

Makes more sense? Sorry if it doesn't english is only my second language.

**Comment by ohmer** [comment]
Note that I have worked around this limitation augmenting `terragrunt` feature with this quick and dirty script: https://gist.github.com/ohmer/40e61ed16afe5d9a46b5de0b7fd6a7d8

I do not have this limitation when using `terramate`. `terramate run <COMMAND>` executes `<COMMAND>` in each stack directories where `terragrunt run-all <command>` executes `terraform <COMMAND>`. For instance I can execute `tflint` with `terramate run tflint`

**Comment by leg100** [comment]
Yup, makes sense. I was under the misapprehension that adsf auto-downloaded tools if the specified version isn't installed. (I've only dabbled with asdf in the past).

Just to need to think how best to implement this.

There could be a key to invoke an abitrary command on the selected modules, e.g. `X`, which when pressed prompts the user to specify the full command to execute.

Or could allow user to map their own keys in the startup configuration, e.g. in the config file:

```yaml
keys:
  X: asdf install terraform
```

**Comment by ohmer** [comment]
Ability to add key mapping via config and invoke abitrary commands sounds like great features, I do not seem them mutually as exclusive. The ability to run with a maximum concurrency of 1 is important for some commands like `terraform init`. Wish I could help, I can't fkin write go...

**Comment by leg100** [comment]
Added [section](https://github.com/leg100/pug?tab=readme-ov-file#multiple-terraform-versions) to README, explaining use of asdf or mise in tandem with Pug to download and install versions terraform.

**Comment by leg100** [comment]
@ohmer https://github.com/leg100/pug/releases/tag/v0.5.2 maps `x` to arbitrary execution, and `u` to `terraform init -upgrade`.

I'll implement user-customisable mappings later on.

**Comment by ohmer** [comment]
Just tested both features, thanks a lot!
