### ISSUE TITLE
Terragrunt support broken (possibly due to output format changes.)

### ISSUE THREAD

**Issue by kaorihinata** [leg100/pug#134]
**Describe the bug**

Attempted to use pug with my previously working infrastructure and it's no longer able to find the workspace (from the logs, it looks like it fails to understand the output of `terragrunt workspace list`) for any of my modules. I suspect this may be related to terragrunt changing the format and destination of their command output in a recent release (I'm using 0.67.14.) Command output appears to be using a log formatter of some sort now and all output appears to be written to stderr. I'm using pug 0.5.3. terraform and tofu work just fine, and terragrunt without pug also works just fine. It's only the combination of pug and terragrunt that is currently failing.

The log reports: `cannot find current workspace: : resource not found`

The previous behavior was:
A list of all workspaces are written to stdout with an asterisk (*) denoting the current active workspace. For example:
`* default`

The new behavior is:
A list of all workspaces are written to stderr with an asterisk (*) denoting the current active workspace using what looks like a log formatter. For example:
`08:02:35.705 STDOUT tofu: * default`

While I could see this change helping upstream since I think their intended use case is in automation, It does break it for us, unfortunately.

**Setup (please complete the following information):**
 - OS [e.g. Ubuntu, macOS] - macOS 15.1 (Sequoia)
 - Shell [e.g. zsh, fish] - zsh
 - Terminal Emulator [e.g. kitty, iterm] - Terminal.app
 - Terminal Multiplexer [e.g. tmux] - None

**To Reproduce**
1. Run `pug -p terragrunt` in a directory containing modules configured to use terragrunt.

**Expected behavior**
I would expect the modules to load correctly, and be able to plan and apply. Currently only init will run without issues.

**Comment by kaorihinata** [comment]
Had a few minutes at lunch. Thankfully there's a flag to fix it. You can just add `--terragrunt-forward-tf-stdout`:

```patch
--- task.go.orig	2024-10-01 12:06:26
+++ task.go	2024-10-01 12:06:43
@@ -185,6 +185,7 @@
 	// TODO: introduce a better way to determine whether terrarunt is in use.
 	// Perhaps use constants for terraform, tofu, and terragrunt.
 	if task.Program == "terragrunt" && f.terragrunt {
+		task.Args = append(task.Args, "--terragrunt-forward-tf-stdout")
 		task.Args = append(task.Args, "--terragrunt-non-interactive")
 	}
 	return task, nil
```

**Comment by leg100** [comment]
Thanks for the detailed exposition. I'll have a look at this when I get a mo.

**Comment by kaorihinata** [comment]
For context, I've grabbed the relevant upstream release as well:
[https://github.com/gruntwork-io/terragrunt/releases/tag/v0.67.0](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.67.0)

**Comment by leg100** [comment]
Ok, adding `--terragrunt-forward-tf-stdout` as you suggest does indeed fix things when using terragrunt v0.67.

However, it breaks if using an old version, in my case terragrunt v0.60:

```
Error parsing command-line flags: flag provided but not defined: -terragrunt-forward-tf-stdout                                                                                                                                                             
```

Couple of approaches:

* Call `terragrunt -v` at startup and add flag only if >= v0.67.
* Damn those using terragrunt < v0.67 and add the flag regardless.

Let me know what you think.

**Comment by kaorihinata** [comment]
Yeah, that's why I used `-U3` for my diff so that it would include your comment about how we should be handling terragrunt. The [recommended installation method](https://terragrunt.gruntwork.io/docs/getting-started/install/) appears to be downloading the binary from their releases page. It looks like the distributions that *are* including terragrunt in their repositories are [mostly above 0.67.0 now as well](https://repology.org/project/terragrunt/versions), Homebrew included. If the user installs and upgrades pug via Homebrew, then they're probably doing the same for terragrunt so you should be fine there. If they installed pug by downloading a release, then I think they're probably more than capable of doing the same for terragrunt. I'm not sure if checking the version would be worth the time given 0.67.0 is already over a month old at this point.

**Comment by leg100** [comment]
Fixed in d4caaff6e7ba3f2b12debb33472eb8498f22e809

**Comment by leg100** [comment]
@kaorihinata @ohmer Please try out 16b0b05. I've gone with @ohmer's suggestion and instead set `TERRAGRUNT_FORWARD_TF_STDOUT=1`. I've tried out both < 0.67 and >= 0.67 and I've confirmed it works with both, so it would appear to an all-round better approach. If you're both happy with this I'll push a release.

**Comment by leg100** [comment]
```bash
go install github.com/leg100/pug@16b0b05
```

**Comment by kaorihinata** [comment]
Works fine here.

**Comment by ohmer** [comment]
Tested v0.5.5-0.20241007170851-16b0b05828de. Works with Terragrunt 0.66.3 and 0.67.16.
