### ISSUE TITLE
Minor interface usability shift-tab expectation to do back

### ISSUE THREAD

**Issue by nokernel** [leg100/pug#49]
**Is your feature request related to a problem? Please describe.**

Only a simple usability expectations.
Personally I am used to press shift-tab for tab to go backwards when changing "window".

**Describe the solution you'd like**
Pressing shift-tab would move backwards

**Describe alternatives you've considered**
None

**Comment by leg100** [comment]
Ok, I'll either add this an additional key for going back in history, or I'll implement the ability for a user to re-define key bindings.

**Comment by leg100** [comment]
Implemented in 7bb8c2b
