### ISSUE TITLE
Keep selected modules when doing action

### ISSUE THREAD

**Issue by nokernel** [leg100/pug#50]
**Is your feature request related to a problem? Please describe.**
* I select a few modules but not all
* I start init
* Selected modules are no longer selected, so doing plan apply one must re-select them.

**Describe the solution you'd like**
Would be nice if pug keeps the selected modules highlighted and selected after an action.

**Describe alternatives you've considered**

Re-selecting modules.

**Additional context**

**Comment by leg100** [comment]
That's a good use case. I actually deliberately designed pug to de-select rows following an action because it felt more "natural". But I'm not so sure now. I'll look into this.
