### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by sysadmind** [leg100/pug#62]
**Describe the bug**
The [installation instructions in the README](https://github.com/leg100/pug?tab=readme-ov-file#install-instructions) describes installing pug with `go install github.com/leg100/pug@latest`. This does not seem to work currently due to some configuration in the go.mod file. The error:
```
# go install github.com/leg100/pug@latest
go: downloading github.com/leg100/pug v0.1.10
go: github.com/leg100/pug@latest (in github.com/leg100/pug@v0.1.10):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Setup (please complete the following information):**
 - OS: Ubuntu
 - Shell: zsh
 - Terminal Emulator: tilix
 - Terminal Multiplexer: N/A
 - Go Version: go version go1.22.2 linux/amd64

**To Reproduce**
1. Open a shell with go installed
2. run `go install github.com/leg100/pug@latest`
3. See error

**Expected behavior**
Go should download and install the latest version of pug

**Screenshots**
N/A

**Additional context**
N/A

**Comment by leg100** [comment]
Thank you for the bug report. I'll have to do something about those replace directives...
