### ISSUE TITLE
go install error

### ISSUE THREAD

**Issue by justaskz** [leg100/pug#75]
I am not a golang user therefore I need help resolving this :D I am using 1.22.4 version

**Describe the bug**

**Setup (please complete the following information):**
 - OS: MacOS
 - Shell zsh
 - Terminal Emulator kitty
 - Terminal Multiplexer tmux

**To Reproduce**
```
go install github.com/leg100/pug@latest
go: github.com/leg100/pug@latest (in github.com/leg100/pug@v0.2.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by leg100** [comment]
Hi @justaskz thanks yes I'm aware of this, there is a fix on master, I'll push it today.

Thanks for the report!

**Comment by leg100** [comment]
@justaskz Fixed. You might need to set `GOPROXY=direct`, i.e.:

```
GOPROXY=direct go install github.com/leg100/pug@latest
```

(`GOPROXY=direct` is only necessary when a new package has only just been released, and the golang proxy servers have not learnt of it yet, and are still serving the previous version).
