### ISSUE TITLE
Support NO_COLOR to turn off the color scheme

### ISSUE THREAD

**Issue by chenrui333** [leg100/pug#93]
Would be good to support NO_COLOR env to disable the color output.

https://no-color.org/

**Comment by leg100** [comment]
Specifying `NO_COLOR` does already turn off colors in Pug, but I noticed the following:

* the current item is no longer highlighted and there is no way to distinguish it
* same with selected items
* the output from terraform processes is still colored

Is this what you are seeing?

Out of interest, what is the use case?

**Comment by chenrui333** [comment]
it is used for CI to check the output in my case, but it would be good to support NO_COLOR in general

**Comment by leg100** [comment]
Can you please confirm whether you are seeing the above?

**Comment by chenrui333** [comment]
yeah, it is fine.
